create-filters
Andrii9991/vue_shop pull request #22
Opened 2023-11-21 17:01 UTC by Andrii9991

2023-11-21 17:19 UTC, kashtan1231 requested changes

2023-11-21 17:19 UTC, kashtan1231 commented on src/components/BaseAccordion.vue
> +  // &__container {
комменты удаляем

2023-11-21 17:19 UTC, kashtan1231 commented on src/components/BaseSelect.vue
> +        alt=""
альты повставляй

2023-11-21 17:19 UTC, kashtan1231 commented on src/views/CatalogPage.vue
> +  // padding: 25px;
комменты

2023-11-21 17:19 UTC, kashtan1231 commented on src/views/CatalogPage.vue
> +  .catalog-page__container {
амперсанд используй

2023-11-21 17:22 UTC, Andrii9991 commented on src/views/CatalogPage.vue
> +  .catalog-page__container {
+

2023-11-21 17:22 UTC, Andrii9991 commented on src/views/CatalogPage.vue
> +  // padding: 25px;
+

2023-11-21 17:23 UTC, Andrii9991 commented on src/components/BaseSelect.vue
> +        alt=""
+

2023-12-02 08:15 UTC, kashtan1231 approved these changes

2023-12-02 08:15 UTC, merged